language: perl
perl:
   - "5.12"

install:
   # Deal with all of the dependencies, quickly and quietly
   - cpanm --quiet --notest --skip-satisfied Devel::Cover::Report::Coveralls
before_script:
   # also initialize submodules recursive
   # - git submodule update --init --recursive
   - cpanm --quiet --notest --skip-satisfied Plack
   - cpanm --quiet --notest --skip-satisfied CGI::SHTML
   - cpanm --quiet --notest --skip-satisfied File::Slurp
script:
   - perl Build.PL
   - ./Build installdeps
   - ./Build verbose=1
   - ./Build test verbose=1
   - sudo ./Build install verbose=1
after_success:
   - cover -test -report coveralls
